export type PlatformData = {
  name: string;
  slug: string;
  url: string;
  ogImage: string;
  accent: string;
  accentDim: string;
  accentBorder: string;
  tagline: string;
  description: string;
  capabilities: string[];
  crossDomain: string;
  stats: { label: string; value: string }[];
  features: { title: string; description: string }[];
  methodology?: { title: string; description: string }[];
  keyInsights: string[];
};

export const platforms: Record<string, PlatformData> = {
  orbital: {
    name: "Orbital Risk Tracker",
    slug: "orbital",
    url: "https://orbitalrisktracker.vercel.app/",
    ogImage: "/images/orbital-og.jpg",
    accent: "#38bdf8",
    accentDim: "rgba(56,189,248,0.15)",
    accentBorder: "rgba(56,189,248,0.25)",
    tagline: "Space Security Intelligence Platform",
    description:
      "Mapping real-world space security incidents across orbit, cyberspace, and the electromagnetic spectrum. The Orbital Risk Tracker provides a policy-grade interface for understanding the strategic vulnerabilities of space-based infrastructure.",
    capabilities: [
      "Satellite constellation risk mapping and vulnerability assessment",
      "Orbital debris field tracking and collision probability modeling",
      "Comprehensive space security incident database with timeline analysis",
      "Electromagnetic spectrum interference and jamming event cataloguing",
      "Space governance gap identification and institutional fragmentation analysis",
      "Launch activity monitoring and dual-use capability tracking",
    ],
    crossDomain:
      "Orbital systems underpin nuclear command-and-control, enable cyber operations through satellite communications, shape the infrastructure upon which lunar governance depends, and create dependencies that cascade across all strategic domains when disrupted.",
    stats: [
      { label: "Orbital Regimes", value: "4" },
      { label: "Incident Categories", value: "6" },
      { label: "Active Constellations", value: "12+" },
      { label: "Threat Vectors", value: "8" },
    ],
    features: [
      {
        title: "Space Security Incident Database",
        description:
          "Comprehensive catalogue of real-world space security events including anti-satellite tests, close-approach maneuvers, signal jamming, and orbital debris-generating events. Each incident mapped by orbital regime, actor, technique, and strategic impact.",
      },
      {
        title: "Constellation Vulnerability Mapping",
        description:
          "Analysis of major satellite constellations\u2014including Starlink, OneWeb, GPS, GLONASS, and BeiDou\u2014assessing single-point-of-failure risks, ground segment dependencies, and cross-link architecture vulnerabilities.",
      },
      {
        title: "Orbital Debris Risk Assessment",
        description:
          "Tracking debris fields generated by ASAT tests and collisions, modeling cascade risk (Kessler syndrome scenarios), and identifying orbital regimes most vulnerable to long-term access denial.",
      },
      {
        title: "Electromagnetic Spectrum Analysis",
        description:
          "Mapping incidents of GPS spoofing, satellite communication jamming, and spectrum interference events. Correlating EM disruption patterns with geopolitical tensions and military operations.",
      },
    ],
    keyInsights: [
      "Space is no longer a sanctuary\u2014it is an active domain of strategic competition where physical and electronic threats converge.",
      "The concentration of critical infrastructure in specific orbital regimes creates systemic vulnerabilities that affect all domains simultaneously.",
      "Ground segment dependencies represent the most accessible attack surface for adversaries seeking to disrupt space-based services.",
      "Orbital debris from a single destructive event can deny access to entire orbital regimes for decades, affecting civilian and military operations alike.",
    ],
  },

  nuclear: {
    name: "Global Nuclear Infrastructure Atlas",
    slug: "nuclear",
    url: "https://globalnuclearinfrastructureatlas.vercel.app/",
    ogImage: "/images/nuclear-og.png",
    accent: "#2dd4bf",
    accentDim: "rgba(45,212,191,0.15)",
    accentBorder: "rgba(45,212,191,0.25)",
    tagline: "Global Nuclear Facility Mapping",
    description:
      "A geospatial atlas of global nuclear facilities, enrichment sites, reactor networks, and strategic posture. Visualizes the physical and political topology of nuclear infrastructure worldwide, from civilian reactors to dual-use enrichment facilities.",
    capabilities: [
      "Global reactor network visualization with capacity and status data",
      "Uranium enrichment facility mapping and centrifuge cascade tracking",
      "Strategic nuclear posture analysis across declared and threshold states",
      "Nuclear governance framework comparison (NPT, IAEA, regional treaties)",
      "Dual-use infrastructure identification and proliferation risk assessment",
      "Spent fuel storage and reprocessing site cataloguing",
    ],
    crossDomain:
      "Nuclear command-and-control depends on orbital communication links and is increasingly vulnerable to cyber intrusion. Contested space governance frameworks shape nuclear posture calculations. Disruptions in any domain can alter escalation dynamics.",
    stats: [
      { label: "Countries Mapped", value: "30+" },
      { label: "Nuclear Facilities", value: "400+" },
      { label: "Reactor Types", value: "6" },
      { label: "Enrichment Sites", value: "20+" },
    ],
    features: [
      {
        title: "Geospatial Facility Mapping",
        description:
          "Interactive map of nuclear facilities worldwide\u2014power reactors, research reactors, enrichment plants, reprocessing facilities, and waste storage sites. Each facility tagged with operational status, capacity, operator, and safeguards status.",
      },
      {
        title: "Enrichment & Fuel Cycle Analysis",
        description:
          "Detailed mapping of the nuclear fuel cycle from uranium mining through enrichment, fabrication, reactor use, reprocessing, and waste disposal. Identifies bottlenecks, dependencies, and dual-use proliferation concerns at each stage.",
      },
      {
        title: "Strategic Posture Dashboard",
        description:
          "Analysis of nuclear-armed states\u2019 force structures, delivery systems, warhead estimates, and doctrinal posture. Tracks modernization programs, arms control compliance, and strategic stability indicators.",
      },
      {
        title: "Governance & Safeguards Framework",
        description:
          "Mapping of international nuclear governance\u2014NPT status, IAEA safeguards agreements, nuclear-weapon-free zones, and bilateral arms control treaties. Identifies governance gaps and institutional fragmentation.",
      },
    ],
    keyInsights: [
      "The global nuclear fuel cycle creates dependencies that cross national boundaries\u2014disruption at any point cascades through the entire supply chain.",
      "Dual-use enrichment technology remains the critical proliferation bottleneck, with identical infrastructure serving civilian energy and weapons programs.",
      "Nuclear command-and-control systems depend on satellite communications and are increasingly exposed to cyber attack vectors.",
      "Institutional fragmentation between civilian nuclear governance (IAEA) and strategic arms control creates dangerous oversight gaps.",
    ],
  },

  space: {
    name: "Space Mandate Atlas",
    slug: "space",
    url: "https://lunar-mandate-atlas.vercel.app/",
    ogImage: "/images/govern-og.png",
    accent: "#a78bfa",
    accentDim: "rgba(167,139,250,0.15)",
    accentBorder: "rgba(167,139,250,0.25)",
    tagline: "Lunar Governance Authority Tracker",
    description:
      "Mapping authority structures in contested lunar governance. Framework analysis across all spacefaring states\u2014who writes the rules, who interprets them, and who decides who participates. Tracking 42 governance documents across 30+ nations with 15+ identified discretion points.",
    capabilities: [
      "Three-stage governance document authority mapping (Humanity, Legitimacy, Authority)",
      "Discretion point registry\u2014governance terms with concentrated interpretive power",
      "Artemis Accords vs ILRS structured coalition comparison across 6 dimensions",
      "Non-aligned state positioning and strategic independence tracking",
      "Cross-framework mandate analysis with boundary power identification",
      "Document corpus analysis covering national strategies, bilateral agreements, and multilateral instruments",
    ],
    crossDomain:
      "Space governance frameworks shape the institutional architecture within which orbital, nuclear, and cyber systems operate. Concentrated interpretive authority in governance documents creates structural vulnerabilities that cascade across all strategic domains.",
    stats: [
      { label: "Documents Analyzed", value: "42" },
      { label: "States Covered", value: "30+" },
      { label: "Discretion Points", value: "15+" },
      { label: "Artemis Signatories", value: "29" },
    ],
    features: [
      {
        title: "Three-Stage Authority Mapping",
        description:
          "Every governance document analyzed through three analytical stages: Humanity Construction (who benefits, how benefit is justified, who is addressed), Legitimacy Production (rules density, justificatory vocabulary, acknowledgement mechanisms), and Authority Architecture (interpretive control, discretion points, boundary power).",
      },
      {
        title: "Discretion Point Registry",
        description:
          "Catalogue of governance terms carrying concentrated interpretive authority\u2014\u201charmful interference,\u201d \u201cdue regard,\u201d \u201cprovince of all mankind,\u201d \u201ccommon heritage of mankind.\u201d Each mapped with textual evidence, holder of discretion, and governance implications.",
      },
      {
        title: "Artemis vs ILRS Coalition Comparison",
        description:
          "Structured side-by-side analysis across six dimensions: mandate style, institutional form, openness logic, infrastructure strategy, political narrative, and authority logic. The Artemis Accords (29 signatories) and ILRS (12 partners) compared as structurally distinct but functionally analogous authority mechanisms.",
      },
      {
        title: "Non-Aligned State Analysis",
        description:
          "12 nations maintaining strategic independence from both coalitions\u2014Indonesia, Turkey, Switzerland, Sweden, Belgium, Austria, Malaysia, Philippines, and others\u2014tracked with their stated positions, space capabilities, and institutional affiliations.",
      },
    ],
    methodology: [
      {
        title: "Humanity Construction",
        description:
          "Who benefits? How is benefit justified? Who is the audience? Tracks referent type (beneficiary horizon, collective subject, scientific commons, future generations), representation rationale, and primary audience for each document.",
      },
      {
        title: "Legitimacy Production",
        description:
          "How detailed are the rules? What values are invoked? How are parties recognized? Analyzes rules density (aspirational to legislative), justificatory vocabulary (safety/sustainability vs equality/development), and acknowledgement mechanisms.",
      },
      {
        title: "Authority Architecture",
        description:
          "Who gets to define ambiguous terms? How many governance terms lack definition? What mechanism concentrates authority? Maps interpretive control, discretion point count, and boundary power type for every document in the corpus.",
      },
    ],
    keyInsights: [
      "Both the Artemis Accords and ILRS deploy universalist language while concentrating interpretive power\u2014the mechanisms differ, but the structural outcome is analogous.",
      "Key governance terms like \u201charmful interference\u201d and \u201cdue regard\u201d remain undefined, creating discretion points where authority accumulates without accountability.",
      "The ILRS partner selection process has no published criteria, concentrating gatekeeping authority in the China-Russia founding axis.",
      "12 non-aligned states represent a potential third path in lunar governance, but lack institutional coordination to challenge either framework.",
    ],
  },

  cyber: {
    name: "Cyber Escalation Atlas",
    slug: "cyber",
    url: "https://cyber-escalation-atlas.vercel.app/",
    ogImage: "/images/cyber-og.jpg",
    accent: "#f59e0b",
    accentDim: "rgba(245,158,11,0.15)",
    accentBorder: "rgba(245,158,11,0.25)",
    tagline: "Strategic Cyber Operations Mapping",
    description:
      "A policy-grade reference mapping how state-linked cyber operations unfold, escalate, and reshape international governance. Charts escalation dynamics, attack techniques, and the pathways through which digital disruption cascades into strategic consequence.",
    capabilities: [
      "State-linked cyber operation case studies with timeline and attribution analysis",
      "Escalation lens analysis\u2014mapping how operations cross thresholds",
      "Attack technique cataloguing aligned with MITRE ATT&CK framework",
      "Cross-domain impact tracing from cyber to physical infrastructure",
      "Governance response mapping\u2014institutional reactions and normative evolution",
      "Strategic signaling analysis\u2014how cyber operations communicate intent",
    ],
    crossDomain:
      "Cyber operations can target satellite ground stations, disrupt nuclear early-warning systems, undermine space governance communications, and create misperception cascades that travel across orbital, nuclear, and governance domains. Digital disruption is rarely contained to cyberspace alone.",
    stats: [
      { label: "Operations Catalogued", value: "50+" },
      { label: "State Actors", value: "15+" },
      { label: "Attack Techniques", value: "40+" },
      { label: "Escalation Pathways", value: "8" },
    ],
    features: [
      {
        title: "Cyber Operation Case Studies",
        description:
          "In-depth analysis of state-linked cyber operations\u2014from Stuxnet to SolarWinds, NotPetya to Colonial Pipeline. Each case mapped with attack vector, technique chain, attribution confidence, strategic context, and cross-domain consequences.",
      },
      {
        title: "Escalation Dynamics Analysis",
        description:
          "Framework for understanding how cyber operations cross escalation thresholds\u2014from espionage to disruption, from disruption to destruction, from digital to physical. Maps the signaling functions and misperception risks at each stage.",
      },
      {
        title: "Attack Technique Catalogue",
        description:
          "Comprehensive catalogue of cyber attack techniques observed in state-linked operations, aligned with MITRE ATT&CK where applicable. Tracks evolution of technique sophistication and defensive countermeasure effectiveness over time.",
      },
      {
        title: "Cross-Domain Impact Tracing",
        description:
          "Mapping how cyber operations cascade beyond cyberspace\u2014disrupting power grids, interfering with satellite communications, degrading nuclear early-warning systems, and creating strategic misperception that alters posture calculations across domains.",
      },
    ],
    keyInsights: [
      "Cyber operations increasingly serve as instruments of strategic signaling, with effects designed to communicate capability and resolve rather than maximize destruction.",
      "The escalation dynamics of cyber conflict remain poorly understood\u2014operations intended as proportionate responses can trigger disproportionate reactions through misperception.",
      "Critical infrastructure interdependence means that a cyber operation targeting one sector inevitably generates cascading effects across orbital, nuclear, and governance domains.",
      "International cyber norms remain nascent and unenforceable, leaving the governance of state-linked cyber operations in a structural vacuum.",
    ],
  },
};
